create table tournament (
    id               bigint generated by default as identity primary key,
    name             varchar(255) not null,
    description      varchar(255) not null,
    visibility       varchar(16)  not null check (visibility in ('PUBLIC', 'PRIVATE')),
    team_count_limit integer      not null check (team_count_limit > 0)
);
