create table users (
    id            bigint generated by default as identity primary key,
    name          varchar(255) not null,
    email         varchar(255) not null unique,
    password_hash varchar(72)  not null,
    created_at    timestamptz  not null default now()
);
